const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("------------------------------------------------------");
  console.log(" Deploying ArtLedger to:", hre.network.name);
  console.log("------------------------------------------------------");

  const [deployer] = await hre.ethers.getSigners();
  console.log("Deployer account:", deployer.address);
  const balance = await hre.ethers.provider.getBalance(deployer.address);
  console.log("Account balance:", hre.ethers.formatEther(balance), "ETH");

  const ArtLedgerFactory = await hre.ethers.getContractFactory("ArtLedger");
  const artLedger = await ArtLedgerFactory.deploy();
  await artLedger.waitForDeployment();

  const contractAddress = await artLedger.getAddress();
  console.log("\n>>> ArtLedger successfully deployed to:", contractAddress);

  // Export contract address and ABI directly to frontend/lib/contract.ts
  const artifactPath = path.join(__dirname, "../artifacts/contracts/ArtLedger.sol/ArtLedger.json");
  if (fs.existsSync(artifactPath)) {
    const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
    const frontendLibDir = path.join(__dirname, "../../frontend/lib");
    if (!fs.existsSync(frontendLibDir)) {
      fs.mkdirSync(frontendLibDir, { recursive: true });
    }

    const contractTsContent = `// Auto-generated by blockchain/scripts/deploy.js
export const ARTLEDGER_ADDRESS = "${contractAddress}" as const;
export const ARTLEDGER_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;

    fs.writeFileSync(path.join(frontendLibDir, "contract.ts"), contractTsContent);
    console.log(">>> Synced ABI & Contract Address to frontend/lib/contract.ts");
  }

  console.log("------------------------------------------------------");
}

main().catch((error) => {
  console.error("Deployment failed:", error);
  process.exitCode = 1;
});
