const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("======================================================");
  console.log(" ArtLedger — Hackathon Showcase Seeding Script");
  console.log("======================================================");

  const signers = await hre.ethers.getSigners();
  const [adminAndArtist, gallerySigner, restorerSigner, appraiserSigner] = signers;

  console.log(">>> Deploying ArtLedger Contract...");
  const ArtLedgerFactory = await hre.ethers.getContractFactory("ArtLedger");
  const artLedger = await ArtLedgerFactory.deploy();
  await artLedger.waitForDeployment();

  const contractAddress = await artLedger.getAddress();
  console.log(">>> Contract deployed at:", contractAddress);

  // 1. Grant Roles
  console.log("\n>>> Configuring Institutional Curator Roles...");
  await artLedger.grantGalleryRole(gallerySigner.address);
  console.log("  [+] Granted GALLERY_ROLE to:", gallerySigner.address);

  await artLedger.grantRestorerRole(restorerSigner.address);
  console.log("  [+] Granted RESTORER_ROLE to:", restorerSigner.address);

  await artLedger.grantAppraiserRole(appraiserSigner.address);
  console.log("  [+] Granted APPRAISER_ROLE to:", appraiserSigner.address);

  // 2. Mint 1 Artwork (Leonardo da Vinci - Salvator Mundi)
  console.log("\n>>> Minting Demonstration Masterpiece (Token #0)...");
  const sampleHash = hre.ethers.keccak256(
    hre.ethers.toUtf8Bytes("ArtLedger-Leonardo-da-Vinci-Salvator-Mundi-Original")
  );
  const sampleCID = "QmZtmD2qtNmR43eDHxNWBbzjGndEwmFqjZBv69b9aXWC2q";
  const tokenURI = `ipfs://${sampleCID}/metadata.json`;

  const mintTx = await artLedger.connect(adminAndArtist).mintArtwork(
    "Leonardo da Vinci",
    "Salvator Mundi",
    1500,
    "Oil on Walnut Panel",
    sampleHash,
    sampleCID,
    tokenURI
  );
  await mintTx.wait();
  console.log("  [+] Artwork Minted successfully! Token ID: #0");
  console.log("      SHA-256 Digest:", sampleHash);

  // 3. Log Event 1: Gallery Custody Transfer & Loan
  console.log("\n>>> Logging Event 1: Gallery Custody Transfer...");
  const event1Tx = await artLedger.connect(gallerySigner).logCustodyEvent(
    0,
    1, // EventType.CustodyTransfer
    "Acquired for international retrospective loan exhibition by curatorial board",
    "National Gallery London, UK"
  );
  await event1Tx.wait();
  console.log("  [+] Logged Event 1 under GALLERY_ROLE");

  // 4. Log Event 2: Restorer Conservation Treatment
  console.log("\n>>> Logging Event 2: Conservation & Restoration Report...");
  const event2Tx = await artLedger.connect(restorerSigner).logCustodyEvent(
    0,
    3, // EventType.Restoration
    "Spectral infrared reflectography scan and archival varnish stabilization",
    "Atelier di Conservazione, Florence"
  );
  await event2Tx.wait();
  console.log("  [+] Logged Event 2 under RESTORER_ROLE");

  // 5. Log Event 3: Appraiser Valuation & Insurance Audit
  console.log("\n>>> Logging Event 3: Official Valuation Appraisal...");
  const event3Tx = await artLedger.connect(appraiserSigner).logCustodyEvent(
    0,
    4, // EventType.Appraisal
    "Formal authenticity audit concluded and insured valuation certified at $450,000,000",
    "Christie's Auction House, New York"
  );
  await event3Tx.wait();
  console.log("  [+] Logged Event 3 under APPRAISER_ROLE");

  // 6. Verify Final State
  const eventCount = await artLedger.getProvenanceCount(0);
  console.log(`\n>>> Total On-Chain Provenance Events on Token #0: ${eventCount} (1 Mint + 3 Curator Events)`);

  // 7. Sync ABI and Deployed Address to Frontend
  const artifactPath = path.join(__dirname, "../artifacts/contracts/ArtLedger.sol/ArtLedger.json");
  if (fs.existsSync(artifactPath)) {
    const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
    const frontendLibDir = path.join(__dirname, "../../frontend/lib");
    if (!fs.existsSync(frontendLibDir)) {
      fs.mkdirSync(frontendLibDir, { recursive: true });
    }

    const contractTsContent = `// Auto-generated by blockchain/scripts/seed-demo.js
export const ARTLEDGER_ADDRESS = "${contractAddress}" as const;
export const ARTLEDGER_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;

    fs.writeFileSync(path.join(frontendLibDir, "contract.ts"), contractTsContent);
    console.log(">>> Synced ABI & Contract Address to frontend/lib/contract.ts");
  }

  console.log("\n======================================================");
  console.log(" Showcase Dataset Successfully Seeded!");
  console.log("======================================================");
}

main().catch((error) => {
  console.error("Seeding failed:", error);
  process.exitCode = 1;
});
